name:                piquet
version:             0.1.0.0
github:              "mmai/piquet"
license:             BSD3
author:              "Henri Bourcereau"
maintainer:          "henri@bourcereau.fr"
copyright:           "2018 Henri Bourcereau"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/piquet#readme>

dependencies:
- base >= 4.7 && < 5
- array
- split
- random
- mtl
- lens
- containers
- ordered-containers
- MonadRandom
- aeson
- aeson-casing
- binary
- time
- wai-app-static
- bytestring
- distributed-process
- distributed-process-simplelocalnet
- distributed-process-supervisor
- network-transport-inmemory
- network-transport-tcp
- megaparsec
- monad-logger
- monad-loops
- resourcet
- stm
- text
- formatting
- transformers
- wai
- wai-websockets
- warp
- websockets
- yaml

library:
  source-dirs: src

executables:
  piquet-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - piquet
    - network
  piquetClient-exe:
    main:                Main.hs
    source-dirs:         client
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - piquet
    - network

tests:
  piquet-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - piquet
